// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package uiauto

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatAction is an auto-generated flat version of Action.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatAction struct {
	Type                *string  `mapstructure:"type" json:"type" cty:"type" hcl:"type"`
	Name                *string  `mapstructure:"name" json:"name" cty:"name" hcl:"name"`
	X                   *int     `mapstructure:"x" json:"x" cty:"x" hcl:"x"`
	Y                   *int     `mapstructure:"y" json:"y" cty:"y" hcl:"y"`
	X2                  *int     `mapstructure:"x2" json:"x2" cty:"x2" hcl:"x2"`
	Y2                  *int     `mapstructure:"y2" json:"y2" cty:"y2" hcl:"y2"`
	DX                  *int     `mapstructure:"dx" json:"dx" cty:"dx" hcl:"dx"`
	DY                  *int     `mapstructure:"dy" json:"dy" cty:"dy" hcl:"dy"`
	Text                *string  `mapstructure:"text" json:"text" cty:"text" hcl:"text"`
	Key                 *string  `mapstructure:"key" json:"key" cty:"key" hcl:"key"`
	Hotkey              *string  `mapstructure:"hotkey" json:"hotkey" cty:"hotkey" hcl:"hotkey"`
	Role                *string  `mapstructure:"role" json:"role" cty:"role" hcl:"role"`
	Label               *string  `mapstructure:"label" json:"label" cty:"label" hcl:"label"`
	LabelContains       *string  `mapstructure:"label_contains" json:"label_contains" cty:"label_contains" hcl:"label_contains"`
	Value               *string  `mapstructure:"value" json:"value" cty:"value" hcl:"value"`
	Selected            *bool    `mapstructure:"selected" json:"selected" cty:"selected" hcl:"selected"`
	Enabled             *bool    `mapstructure:"enabled" json:"enabled" cty:"enabled" hcl:"enabled"`
	Style               *string  `mapstructure:"style" json:"style" cty:"style" hcl:"style"`
	TextFieldByPosition *string  `mapstructure:"text_field_by_position" json:"text_field_by_position" cty:"text_field_by_position" hcl:"text_field_by_position"`
	ClearFirst          *bool    `mapstructure:"clear_first" json:"clear_first" cty:"clear_first" hcl:"clear_first"`
	Region              *string  `mapstructure:"region" json:"region" cty:"region" hcl:"region"`
	Match               *string  `mapstructure:"match" json:"match" cty:"match" hcl:"match"`
	Scene               *string  `mapstructure:"scene" json:"scene" cty:"scene" hcl:"scene"`
	TimeoutSeconds      *int     `mapstructure:"timeout_seconds" json:"timeout_seconds" cty:"timeout_seconds" hcl:"timeout_seconds"`
	Args                []string `mapstructure:"args" json:"args" cty:"args" hcl:"args"`
}

// FlatMapstructure returns a new FlatAction.
// FlatAction is an auto-generated flat version of Action.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Action) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatAction)
}

// HCL2Spec returns the hcl spec of a Action.
// This spec is used by HCL to read the fields of Action.
// The decoded values from this spec will then be applied to a FlatAction.
func (*FlatAction) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"type":                   &hcldec.AttrSpec{Name: "type", Type: cty.String, Required: false},
		"name":                   &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"x":                      &hcldec.AttrSpec{Name: "x", Type: cty.Number, Required: false},
		"y":                      &hcldec.AttrSpec{Name: "y", Type: cty.Number, Required: false},
		"x2":                     &hcldec.AttrSpec{Name: "x2", Type: cty.Number, Required: false},
		"y2":                     &hcldec.AttrSpec{Name: "y2", Type: cty.Number, Required: false},
		"dx":                     &hcldec.AttrSpec{Name: "dx", Type: cty.Number, Required: false},
		"dy":                     &hcldec.AttrSpec{Name: "dy", Type: cty.Number, Required: false},
		"text":                   &hcldec.AttrSpec{Name: "text", Type: cty.String, Required: false},
		"key":                    &hcldec.AttrSpec{Name: "key", Type: cty.String, Required: false},
		"hotkey":                 &hcldec.AttrSpec{Name: "hotkey", Type: cty.String, Required: false},
		"role":                   &hcldec.AttrSpec{Name: "role", Type: cty.String, Required: false},
		"label":                  &hcldec.AttrSpec{Name: "label", Type: cty.String, Required: false},
		"label_contains":         &hcldec.AttrSpec{Name: "label_contains", Type: cty.String, Required: false},
		"value":                  &hcldec.AttrSpec{Name: "value", Type: cty.String, Required: false},
		"selected":               &hcldec.AttrSpec{Name: "selected", Type: cty.Bool, Required: false},
		"enabled":                &hcldec.AttrSpec{Name: "enabled", Type: cty.Bool, Required: false},
		"style":                  &hcldec.AttrSpec{Name: "style", Type: cty.String, Required: false},
		"text_field_by_position": &hcldec.AttrSpec{Name: "text_field_by_position", Type: cty.String, Required: false},
		"clear_first":            &hcldec.AttrSpec{Name: "clear_first", Type: cty.Bool, Required: false},
		"region":                 &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"match":                  &hcldec.AttrSpec{Name: "match", Type: cty.String, Required: false},
		"scene":                  &hcldec.AttrSpec{Name: "scene", Type: cty.String, Required: false},
		"timeout_seconds":        &hcldec.AttrSpec{Name: "timeout_seconds", Type: cty.Number, Required: false},
		"args":                   &hcldec.AttrSpec{Name: "args", Type: cty.List(cty.String), Required: false},
	}
	return s
}

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Enabled         *bool        `mapstructure:"enabled" json:"enabled" cty:"enabled" hcl:"enabled"`
	VNCHost         *string      `mapstructure:"vnc_host" json:"vnc_host" cty:"vnc_host" hcl:"vnc_host"`
	VNCPort         *int         `mapstructure:"vnc_port" json:"vnc_port" cty:"vnc_port" hcl:"vnc_port"`
	VNCPassword     *string      `mapstructure:"vnc_password" json:"vnc_password" cty:"vnc_password" hcl:"vnc_password"`
	VNCDoPath       *string      `mapstructure:"vncdo_path" json:"vncdo_path" cty:"vncdo_path" hcl:"vncdo_path"`
	CGToolPath      *string      `mapstructure:"cgtool_path" json:"cgtool_path" cty:"cgtool_path" hcl:"cgtool_path"`
	UIBackend       *string      `mapstructure:"ui_backend" json:"ui_backend" cty:"ui_backend" hcl:"ui_backend"`
	ArtifactDir     *string      `mapstructure:"artifact_dir" json:"artifact_dir" cty:"artifact_dir" hcl:"artifact_dir"`
	ScreenshotMode  *string      `mapstructure:"screenshot_mode" json:"screenshot_mode" cty:"screenshot_mode" hcl:"screenshot_mode"`
	WindowTitle     *string      `mapstructure:"window_title" json:"window_title" cty:"window_title" hcl:"window_title"`
	DetectorCommand []string     `mapstructure:"detector_command" json:"detector_command" cty:"detector_command" hcl:"detector_command"`
	Actions         []FlatAction `mapstructure:"actions" json:"actions" cty:"actions" hcl:"actions"`
	Scenes          []FlatScene  `mapstructure:"scenes" json:"scenes" cty:"scenes" hcl:"scenes"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"enabled":          &hcldec.AttrSpec{Name: "enabled", Type: cty.Bool, Required: false},
		"vnc_host":         &hcldec.AttrSpec{Name: "vnc_host", Type: cty.String, Required: false},
		"vnc_port":         &hcldec.AttrSpec{Name: "vnc_port", Type: cty.Number, Required: false},
		"vnc_password":     &hcldec.AttrSpec{Name: "vnc_password", Type: cty.String, Required: false},
		"vncdo_path":       &hcldec.AttrSpec{Name: "vncdo_path", Type: cty.String, Required: false},
		"cgtool_path":      &hcldec.AttrSpec{Name: "cgtool_path", Type: cty.String, Required: false},
		"ui_backend":       &hcldec.AttrSpec{Name: "ui_backend", Type: cty.String, Required: false},
		"artifact_dir":     &hcldec.AttrSpec{Name: "artifact_dir", Type: cty.String, Required: false},
		"screenshot_mode":  &hcldec.AttrSpec{Name: "screenshot_mode", Type: cty.String, Required: false},
		"window_title":     &hcldec.AttrSpec{Name: "window_title", Type: cty.String, Required: false},
		"detector_command": &hcldec.AttrSpec{Name: "detector_command", Type: cty.List(cty.String), Required: false},
		"actions":          &hcldec.BlockListSpec{TypeName: "actions", Nested: hcldec.ObjectSpec((*FlatAction)(nil).HCL2Spec())},
		"scenes":           &hcldec.BlockListSpec{TypeName: "scenes", Nested: hcldec.ObjectSpec((*FlatScene)(nil).HCL2Spec())},
	}
	return s
}

// FlatScene is an auto-generated flat version of Scene.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatScene struct {
	Name          *string      `mapstructure:"name" json:"name" cty:"name" hcl:"name"`
	MatchText     []string     `mapstructure:"match_text" json:"match_text" cty:"match_text" hcl:"match_text"`
	MatchControls []FlatAction `mapstructure:"match_controls" json:"match_controls" cty:"match_controls" hcl:"match_controls"`
	Actions       []FlatAction `mapstructure:"actions" json:"actions" cty:"actions" hcl:"actions"`
}

// FlatMapstructure returns a new FlatScene.
// FlatScene is an auto-generated flat version of Scene.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Scene) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatScene)
}

// HCL2Spec returns the hcl spec of a Scene.
// This spec is used by HCL to read the fields of Scene.
// The decoded values from this spec will then be applied to a FlatScene.
func (*FlatScene) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":           &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"match_text":     &hcldec.AttrSpec{Name: "match_text", Type: cty.List(cty.String), Required: false},
		"match_controls": &hcldec.BlockListSpec{TypeName: "match_controls", Nested: hcldec.ObjectSpec((*FlatAction)(nil).HCL2Spec())},
		"actions":        &hcldec.BlockListSpec{TypeName: "actions", Nested: hcldec.ObjectSpec((*FlatAction)(nil).HCL2Spec())},
	}
	return s
}
